{{- $fullName := include "spire-server.fullname" . -}}
{{- $labels := include "spire-server.labels" . }}
{{ include "spire-lib.ingress-template" (dict "ingress" .Values.ingress "name" $fullName "svcName" $fullName "port" .Values.service.port "labels" $labels) }}
