{{- if eq (.Values.controllerManager.enabled | toString) "true" }}
{{- if eq .Values.controllerManager.validatingWebhookConfiguration.failurePolicy "Fail" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spire-server.serviceAccountName" . }}-post-install
  namespace: {{ include "spire-server.namespace" . }}
  labels:
    {{- include "spire-server.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "spire-server.fullname" . }}-post-install
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["get", "list", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spire-server.fullname" . }}-post-install
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
subjects:
  - kind: ServiceAccount
    name: {{ include "spire-server.serviceAccountName" . }}-post-install
    namespace: {{ include "spire-server.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "spire-server.fullname" . }}-post-install
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "spire-server.fullname" . }}-post-install
  namespace: {{ include "spire-server.namespace" . }}
  labels:
    {{- include "spire-server.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
spec:
  template:
    metadata:
      name: {{ include "spire-server.fullname" . }}-post-install
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "spire-server.serviceAccountName" . }}-post-install
      containers:
      - name: post-install-job
        image: bitnami/kubectl
        command:
        - /bin/sh
        - -c
        - |
          kubectl patch validatingwebhookconfiguration {{ include "spire-controller-manager.fullname" . }}-webhook --type='strategic' -p "{\"webhooks\":[{\"name\":\"vclusterspiffeid.kb.io\",\"failurePolicy\":\"{{ .Values.controllerManager.validatingWebhookConfiguration.failurePolicy }}\"}]}"
{{- end }}
{{- end }}
