# Role to be able to push certificate bundles to a configmap
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spire-server.fullname" . }}-bundle
  namespace: {{ .Values.notifier.k8sbundle.namespace | default .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: [configmaps]
    resourceNames: [{{ .Values.bundleConfigMap }}]
    verbs:
      - get
      - patch
{{- if and .Values.upstreamAuthority.certManager.enabled .Values.upstreamAuthority.certManager.rbac.create }}
---
# Role to be able to manage cert requests with Cert-Manager
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spire-server.fullname" . }}-cm
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["cert-manager.io"]
    resources:
      - certificaterequests
    verbs:
      - list
      - get
      - create
      - delete
      - patch
      - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spire-server.fullname" . }}-cm
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "spire-server.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "spire-server.fullname" . }}-cm
  apiGroup: rbac.authorization.k8s.io
{{- end }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spire-server.fullname" . }}-bundle
  namespace: {{ .Values.notifier.k8sbundle.namespace | default .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "spire-server.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "spire-server.fullname" . }}-bundle
  apiGroup: rbac.authorization.k8s.io

{{- if and .Values.nodeAttestor.k8sPsat.enabled }}
---
# ClusterRole to allow spire-server node attestor to query Token Review API
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spire-server.fullname" . }}
rules:
  - apiGroups: [authentication.k8s.io]
    resources: [tokenreviews]
    verbs:
      - get
      - watch
      - list
      - create
  - apiGroups: [""]
    resources: [nodes, pods]
    verbs:
      - get
      - list
---
# Binds above cluster role to spire-server service account
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spire-server.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "spire-server.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "spire-server.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
