{{- if ne .Values.dataStore.sql.databaseType "sqlite3" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spire-server.fullname" . }}-dbpw
  namespace: {{ include "spire-server.namespace" . }}
data:
  DBPW: {{ .Values.dataStore.sql.password | b64enc }}
{{- end }}
