spire-server:
  enabled: true
  upstreamAuthority:
    spire:
      enabled: true
      server:
        address: spire-server.spire-root-server
  controllerManager:
    enabled: true
    identities:
      spiffeIDTemplate: spiffe://{{ .TrustDomain }}/k8s/{{ .ClusterName }}/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodSpec.ServiceAccountName }}

spiffe-oidc-discovery-provider:
  enabled: true
  insecureScheme:
    enabled: true

upstream-spiffe-csi-driver:
  enabled: true

upstream-spire-agent:
  enabled: true
  server:
    address: spire-server.spire-root-server
