global:
  telemetry:
    prometheus:
      enabled: false

spiffe-oidc-discovery-provider:
  enabled: true
  insecureScheme:
    enabled: true
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    capabilities:
      drop: [ALL]
    seccompProfile:
      type: RuntimeDefault

spire-server:
  nodeAttestor:
    k8sPsat:
      serviceAccountAllowList: ["spire-system:spire-agent"]
  notifier:
    k8sbundle:
      namespace: spire-system
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    capabilities:
      drop: [ALL]
    seccompProfile:
      type: RuntimeDefault
  controllerManager:
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      capabilities:
        drop: [ALL]
      seccompProfile:
        type: RuntimeDefault
  tornjak:
    enabled: true
    image:
      registry: ghcr.io
      repository: spiffe/tornjak-be
      pullPolicy: IfNotPresent
      version: "v1.0.2"
    config:
      backend:
        apiServerURL: "http://localhost:10000/"
        dataStore:
          driver: "sqlite3"
          file: "/run/spire/data/tornjak.sqlite3"

tornjak-frontend:
  enabled: true
  image:
    registry: ghcr.io
    repository: spiffe/tornjak-fe
    pullPolicy: IfNotPresent
    version: "v1.0.2"
  imagePullSecrets: []
  nameOverride: ""
  namespaceOverride: ""
  fullnameOverride: ""
  serviceAccount:
    create: true
    annotations: {}
    name: ""
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    capabilities:
      drop: [ALL]
    seccompProfile:
      type: RuntimeDefault
  service:
    type: ClusterIP
    port: 3000
  apiServerURL: "http://localhost:10000/"
