spire-server:
  tornjak:
    enabled: true

tornjak-frontend:
  enabled: true
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    readOnlyRootFilesystem: false
    capabilities:
      drop: [ALL]
    seccompProfile:
      type: RuntimeDefault
  service:
    type: ClusterIP
    port: 3000
  apiServerURL: "http://localhost:10000/"
