apiVersion: v2
name: spire-server
description: A Helm chart to install the SPIRE server.
type: application
version: 0.1.0
appVersion: "1.6.3"
dependencies:
  - name: postgresql
    condition: postgresql.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 12.2.2
  - name: mysql
    condition: mysql.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 9.7.2
