global:
  spire:
    clusterName: production
    trustDomain: production.other
    jwtIssuer: oidc-discovery.production.other

spire-server:
  ca_subject:
    country: US
    organization: Production
    common_name: production.other

  ingress:
    hosts:
      - host: spire-server.production.other
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - spire-server.production.other
  federation:
    ingress:
      hosts:
        - host: spire-server-federation.production.other
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - spire-server-federation.production.other
          secretName: tls-cert

spiffe-oidc-discovery-provider:
  ingress:
    hosts:
      - host: oidc-discovery.production.other
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: tls-cert
        hosts:
          - oidc-discovery.production.other

