apiVersion: v2
name: spire-lib
description: A library of helper templates for spire
type: library
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/spiffe/helm-charts/tree/main/charts/spire
sources:
  - https://github.com/spiffe/helm-charts/tree/main/charts/spire
icon: https://spiffe.io/img/logos/spire/icon/color/spire-icon-color.png
maintainers:
  - name: marcofranssen
    email: marco.franssen@gmail.com
    url: https://marcofranssen.nl
  - name: kfox1111
    email: Kevin.Fox@pnnl.gov
  - name: faisal-memon
    email: fymemon@yahoo.com
  - name: edwbuck
    email: edwbuck@gmail.com
