name: Shellcheck

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, edited]
    paths:
      - .github/workflows/shellcheck.yaml
      - '**/*.sh'

concurrency:
  group: ${{ github.ref }}-shellcheck
  cancel-in-progress: true

env:
  SHELLCHECK_VERSION: v0.9.0

jobs:
  checks:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Run Shellcheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          format: gcc
          version: ${{ env.SHELLCHECK_VERSION }}
